# Generated by Django 4.0.1 on 2023-01-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantas',
            new_name='Vehiculo',
        ),
    ]
