# Generated by Django 4.0.1 on 2023-01-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_plantas_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('tipoPlanta', models.CharField(max_length=20, verbose_name='Tipo de Planta')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
