# Generated by Django 4.0.1 on 2023-01-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plantas_delete_vehiculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantas',
            new_name='Planta',
        ),
    ]
