# Generated by Django 4.0.1 on 2023-01-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_plantas_planta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='tipoPlanta',
            new_name='nombrePlanta',
        ),
        migrations.AddField(
            model_name='planta',
            name='precio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Nombre de la categoria'),
        ),
    ]
