# Generated by Django 4.0.1 on 2023-01-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_tipoplanta_planta_nombreplanta_planta_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='nombrePlanta',
            field=models.CharField(max_length=20, verbose_name='Nombre Planta'),
        ),
    ]
