# Generated by Django 4.0.1 on 2023-01-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_items_carrito_producto_tipoproducto_tipousuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombrePlanta', models.CharField(max_length=20, verbose_name='Nombre Planta')),
                ('precio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Items_Carrito',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
