# Generated by Django 4.0.1 on 2023-01-19 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tipoproducto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='created_at',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='planta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='planta',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='updated_at',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
