# Generated by Django 4.0.1 on 2023-01-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_planta_created_at_planta_imagen_planta_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
