# Generated by Django 4.0.5 on 2023-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_usuario_created_at_remove_usuario_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='codigo',
        ),
        migrations.AddField(
            model_name='planta',
            name='id',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False, verbose_name='id'),
            preserve_default=False,
        ),
    ]
