# Generated by Django 4.0.5 on 2023-01-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_planta_imagen_planta_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='imagen',
        ),
    ]
